apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
    {{- with .Values.kafka.additionalAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "strimzi-cluster-instance.labels" . | nindent 4 }}
    {{- with .Values.kafka.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "strimzi-cluster-instance.fullname" . }}
spec:
  kafka:
    {{- if .Values.kafka.brokerRackInitImage }}
    brokerRackInitImage: {{ .Values.kafka.brokerRackInitImage }}
    {{- end }}
    {{- with .Values.kafka.config }}
    config:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    listeners:
{{- /* Render listeners as a YAML list, merging .Values.kafka.listeners and additionalListeners */}}
      {{- $brokerPool := dict }}
      {{- range $.Values.nodePools }}
        {{- if eq .name "broker" }}
          {{- $_ := set $brokerPool "pool" . }}
        {{- end }}
      {{- end }}
      {{- $all := concat .Values.kafka.listeners .Values.kafka.additionalListeners }}
      {{- range $i, $listener := $all }}
        {{- if $listener.name }}
      - name: {{ $listener.name }}
        port: {{ $listener.port }}
        type: {{ ternary "cluster-ip" $listener.type (eq $listener.type "gateway") }}
        tls: {{ $listener.tls }}
        {{- if $listener.configuration }}
        configuration:
          {{- if and $listener.configuration.bootstrap (ne $listener.type "gateway") }}
          bootstrap:
            host: {{ $listener.configuration.bootstrap.host }}
          {{- end }}
          {{- if $listener.configuration.brokerCertChainAndKey }}
          brokerCertChainAndKey:
            secretName: {{ $listener.configuration.brokerCertChainAndKey.secretName }}
            certificate: {{ $listener.configuration.brokerCertChainAndKey.certificate }}
            key: {{ $listener.configuration.brokerCertChainAndKey.key }}
          {{- end }}
          createBootstrapService: {{ $listener.configuration.createBootstrapService | default true }}
          {{- if and (or (eq $listener.type "ingress") (eq $listener.type "loadBalancer")) $listener.configuration.hostTemplate }}
          hostTemplate: {{ $listener.configuration.hostTemplate }}
          {{- end }}
          {{- if and (eq $listener.type "gateway") $listener.configuration.hostTemplate }}
          brokers:
            {{- $hostTemplate := $listener.configuration.hostTemplate }}
            {{- $ttl := "60" }}
            {{- with $brokerPool.pool }}
              {{- $replicas := .replicas | int }}
              {{- $startId := 100 }}
              {{- range $j, $e := until $replicas }}
            - broker: {{ add $startId $j }}
              advertisedHost: {{ replace "{nodeId}" (print (add $startId $j)) $hostTemplate }}
              advertisedPort: {{ $listener.port }}
              {{- /* Add annotations and labels to the listener entry, not the Kafka root */}}
              {{- if $listener.additionalBrokerAnnotations }}
              annotations:
                {{- range $k, $v := $listener.additionalBrokerAnnotations }}
                {{ $k }}: {{ replace "{nodeId}" (print (add $startId $j)) $v | quote }}
                {{- end }}
              {{- end }}
              {{- if $listener.additionalBrokerLabels }}
              labels:
                {{- range $k, $v := $listener.additionalBrokerLabels }}
                {{ $k }}: {{ replace "{nodeId}" (print (add $startId $j)) $v | quote }}
                {{- end }}
              {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
    {{- if .Values.kafka.metadataVersion }}
    metadataVersion: {{ .Values.kafka.metadataVersion }}
    {{- end }}
    {{- if .Values.kafka.rack }}
    rack:
      {{- toYaml .Values.kafka.rack | nindent 6 }}
    {{- end }}
    {{- if .Values.kafka.version }}
    version: {{ .Values.kafka.version }}
    {{- end }}
  cruiseControl:
    {{- with .Values.kafka.cruiseControl.config }}
    config:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.kafka.cruiseControl.brokerCapacity }}
    brokerCapacity:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    resources:
      {{- toYaml .Values.kafka.cruiseControl.resources | nindent 6 }}
    {{- with .Values.kafka.cruiseControl.template.pod }}
    template:
      pod:
        {{- with .metadata }}
        metadata:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .affinity }}
        affinity:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .tolerations }}
        tolerations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .topologySpreadConstraints }}
        topologySpreadConstraints:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .priorityClassName }}
        priorityClassName: {{ .priorityClassName }}
        {{- end }}
        {{- if .tmpDirSizeLimit }}
        tmpDirSizeLimit: {{ .tmpDirSizeLimit }}
        {{- end }}
        {{- with .volumes }}
        volumes:
          {{- toYaml . | nindent 8 }}
        {{- end }}
    {{- end }}
  entityOperator:
    resources:
      {{- toYaml .Values.kafka.entityOperator.resources | nindent 6 }}
    {{- with .Values.kafka.entityOperator.template.pod }}
    template:
      pod:
        {{- with .metadata }}
        metadata:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .affinity }}
        affinity:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .tolerations }}
        tolerations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .topologySpreadConstraints }}
        topologySpreadConstraints:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .priorityClassName }}
        priorityClassName: {{ .priorityClassName }}
        {{- end }}
        {{- if .tmpDirSizeLimit }}
        tmpDirSizeLimit: {{ .tmpDirSizeLimit }}
        {{- end }}
        {{- with .volumes }}
        volumes:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    topicOperator:
      {{- if.Values.kafka.entityOperator.topicOperator.watchAnyNamespace }}
      {{- else }}      
      {{- if .Values.kafka.entityOperator.topicOperator.watchedNamespace }}
      watchedNamespace: {{ .Values.kafka.entityOperator.topicOperator.watchedNamespace }}
      {{- else }}
      watchedNamespace: {{ .Release.Namespace }}
      {{- end }}
      {{- end }}
      
    userOperator:
      {{- if.Values.kafka.entityOperator.userOperator.watchAnyNamespace }}
      {{- else }}      
      {{- if .Values.kafka.entityOperator.userOperator.watchedNamespace }}
      watchedNamespace: {{ .Values.kafka.entityOperator.userOperator.watchedNamespace }}
      {{- else }}
      watchedNamespace: {{ .Release.Namespace }}
      {{- end }}
      {{- end }}
