{{- range .Values.nodePools }}
{{- $poolName := .name }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  annotations:
    {{- with .additionalAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "strimzi-cluster-instance.labels" $ | nindent 4 }}
    strimzi.io/cluster: {{ include "strimzi-cluster-instance.fullname" $ }}
    {{- with .additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "strimzi-cluster-instance.fullname" $ }}-{{ .name }}
spec:
  template:
    pod:
      {{- with .template.pod.metadata }}
      metadata:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .template.pod.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $hasAffinity := false }}
      {{- if .template.pod.affinity }}
        {{- if or .template.pod.affinity.nodeAffinity .template.pod.affinity.podAffinity .template.pod.affinity.podAntiAffinity }}
          {{- $hasAffinity = true }}
        {{- end }}
      {{- end }}

      {{- if $hasAffinity }}
      affinity:
        {{- with .template.pod.affinity.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .template.pod.affinity.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .template.pod.affinity.podAntiAffinity }}
        podAntiAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- else }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: strimzi.io/cluster
                    operator: In
                    values:
                      - {{ include "strimzi-cluster-instance.fullname" $ }}
                  - key: strimzi.io/pool-name
                    operator: In
                    values:
                      - {{ include "strimzi-cluster-instance.fullname" $ }}-{{ $poolName }}
              topologyKey: "kubernetes.io/hostname"
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: strimzi.io/cluster
                      operator: In
                      values:
                        - {{ include "strimzi-cluster-instance.fullname" $ }}
                    - key: app.kubernetes.io/component
                      operator: Exists
                    - key: app.kubernetes.io/component
                      operator: NotIn
                      values:
                        {{- range $.Values.nodePools }}
                        {{- if eq .name $poolName }}
                        {{- with .template.pod.metadata.labels }}
                        {{- with (index . "app.kubernetes.io/component") }}
                        - {{ . }}
                        {{- end }}
                        {{- end }}
                        {{- end }}
                        {{- end }}
                topologyKey: "kubernetes.io/hostname"
      {{- end }}
      {{- with .template.pod.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .template.pod.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .template.pod.topologySpreadConstraints | nindent 8 }}
      {{- else }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: {{ $.Values.defaultTopologySpreadKey | default "topology.kubernetes.io/zone" }}
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              strimzi.io/cluster: {{ include "strimzi-cluster-instance.fullname" $ }}
              strimzi.io/pool-name: {{ include "strimzi-cluster-instance.fullname" $ }}-{{ $poolName }}
      {{- end }}
      {{- if .template.pod.priorityClassName }}
      priorityClassName: {{ .priorityClassName }}
      {{- end }}
      {{- if .template.pod.tmpDirSizeLimit }}
      tmpDirSizeLimit: {{ .tmpDirSizeLimit }}
      {{- end }}
      {{- with .template.pod.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  replicas: {{ .replicas }}
  roles:
    {{- range .roles }}
    - {{ . }}
    {{- end }}
  {{- with .storage }}
  storage:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
