apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: envoyproxy-crds
  namespace: envoy-gateway-system
spec:
  releaseName: gateway-crds
  chart:
    spec:
      chart: gateway-helm
      version: "0.0.0-latest" #"1.6.1"
      sourceRef:
        kind: HelmRepository
        name: envoyproxy-charts
        namespace: flux-system
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    crds:
      envoyGateway: 
        enabled: true
      gatewayAPI: 
        enabled: true
        channel: experimental
