apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: envoyproxy
  namespace: envoy-gateway-system
spec:
  releaseName: envoyproxy
  chart:
    spec:
      chart: gateway-helm
      version: "1.4.1"
      sourceRef:
        kind: HelmRepository
        name: envoyproxy-charts
        namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 5m
  values:
    deployment:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: test.io/role
                      operator: In
                      values:
                        - "gateway"
        tolerations:
          - operator: Exists
