apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: envoyproxy
  namespace: envoy-gateway-system
spec:
  releaseName: envoyproxy
  chart:
    spec:
      chart: gateway-helm
      version: "0.0.0-latest" #"1.6.1"
      sourceRef:
        kind: HelmRepository
        name: envoyproxy-charts
        namespace: flux-system
  dependsOn:
    - name: envoyproxy-crds
      namespace: envoy-gateway-system
    - name: cert-manager
      namespace: cert-manager
  interval: 5m
  install:
    skipCRDs: true
  upgrade:
    skipCRDs: true
  values:
    deployment:
      replicas: 1
      pod:
        tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: ingress-ready
                  operator: In
                  values:
                  - "true"
