apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gateway
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: raw
      sourceRef:
        kind: HelmRepository
        name: bedag
        namespace: flux-system
      version: "2.0.2"
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: trust-manager
      namespace: cert-manager
    - name: envoyproxy
      namespace: envoy-gateway-system
  values:
    resources:
      -
        apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: cluster-gateway-cert
          namespace: envoy-gateway-system
        spec:
          dnsNames:
          - '*.apps.gateway.api.test'
          - '*.strimzi.gateway.api.test'
          issuerRef:
            kind: ClusterIssuer
            name: cluster-ca-issuer
          privateKey:
            algorithm: ECDSA
            encoding: PKCS8
            size: 256
          secretName: cluster-gateway-cert
          subject:
            organizations:
            - my-org
          usages:
          - server auth
          - client auth
      -
        apiVersion: gateway.envoyproxy.io/v1alpha1
        kind: EnvoyProxy
        metadata:
          name: cluster-gateway
          namespace: envoy-gateway-system
        spec:
          provider:
            type: Kubernetes
            kubernetes:
              envoyService:
                type: NodePort
                patch:
                  value:
                    spec:
                      ports:
                      # Port 9094 for Kafka TLS traffic
                      - name: kafka-port
                        nodePort: 30994
                        port: 9094
                        protocol: TCP
                        targetPort: 9094
                      # Port 9443 for HTTPS traffic
                      - name: https-port
                        nodePort: 30943
                        port: 9443
                        protocol: TCP
                        targetPort: 9443      
          telemetry:
            metrics:
              sinks:
                - type: OpenTelemetry
                  openTelemetry:
                    host: agent-collector.opentelemetry-operator-system.svc.cluster.local
                    port: 4317          
            tracing:
              # sample 100% of requests
              samplingRate: 100
              provider:
                host: agent-collector.opentelemetry-operator-system.svc.cluster.local
                port: 4317
                type: OpenTelemetry

            accessLog:
              settings:
                - format:
                    type: Text
                    text: |
                      [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"
                  sinks:
                    - type: OpenTelemetry
                      openTelemetry:
                        host: agent-collector.opentelemetry-operator-system.svc.cluster.local
                        port: 4317                        
      - 
        apiVersion: gateway.envoyproxy.io/v1alpha1
        kind: EnvoyProxy
        metadata:
          name: management-gateway
          namespace: envoy-gateway-system
        spec:
          provider:
            type: Kubernetes
            kubernetes:
              envoyService:
                type: NodePort
                patch:
                  value:
                    spec:
                      ports:
                      # Port 49443 for management HTTPS traffic (no telemetry)
                      - name: mgmt-https-port
                        nodePort: 30949
                        port: 49443
                        protocol: TCP
                        targetPort: 49443
          # No telemetry configuration for management gateway
      - 
        apiVersion: gateway.networking.k8s.io/v1
        kind: GatewayClass
        metadata:
          name: cluster-gateway-class
          namespace: envoy-gateway-system
        spec:
          controllerName: gateway.envoyproxy.io/gatewayclass-controller
          parametersRef:
            group: gateway.envoyproxy.io
            kind: EnvoyProxy
            name: cluster-gateway
            namespace: envoy-gateway-system
      -
        apiVersion: gateway.networking.k8s.io/v1
        kind: GatewayClass
        metadata:
          name: management-gateway-class
          namespace: envoy-gateway-system
        spec:
          controllerName: gateway.envoyproxy.io/gatewayclass-controller
          parametersRef:
            group: gateway.envoyproxy.io
            kind: EnvoyProxy
            name: management-gateway
            namespace: envoy-gateway-system
      -
        apiVersion: gateway.networking.k8s.io/v1
        kind: Gateway
        metadata:
          name: management-gateway
          namespace: envoy-gateway-system
        spec:
          gatewayClassName: management-gateway-class
          listeners:
          - name: mgmt-https-listener
            protocol: HTTPS
            port: 49443
            tls:
              mode: Terminate
              certificateRefs:
              - kind: Secret
                name: cluster-gateway-cert
                namespace: envoy-gateway-system
            allowedRoutes:
              namespaces:
                from: All
      -
        apiVersion: gateway.networking.k8s.io/v1
        kind: Gateway
        metadata:
          name: cluster-gateway
          # Envoy Gateway can control gateways in all namespaces. Depending on your
          # cluster permissions model, a Gateway can be in the envoy-gateway-system namespace
          # or in the same namespace as your applications.
        spec:
          gatewayClassName: cluster-gateway-class
          listeners:
          - name: kafka-listener
            protocol: TLS
            port: 9094
            tls:
              mode: Passthrough
            allowedRoutes:
              namespaces:
                from: All
          - name: https-listener
            protocol: HTTPS
            port: 9443
            tls:
              mode: Terminate
              certificateRefs:
              - kind: Secret
                name: cluster-gateway-cert
                namespace: envoy-gateway-system
            allowedRoutes:
              namespaces:
                from: All