apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: localregistry
  namespace: flux-system
spec:
  type: oci
  url: oci://kind-registry:5000/dev/charts/
  insecure: true
  interval: 1m
