apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: opentelemetry-operator-system
spec:
  releaseName: opentelemetry-operator
  chart:
    spec:
      chart: opentelemetry-operator
      version: "0.106.0"
      sourceRef:
        kind: HelmRepository
        name: opentelemetry-helm
        namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 5m
  values: {}