apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: otel-logs-collector
  namespace: opentelemetry-operator-system
spec:
  releaseName: otel-logs-collector
  chart:
    spec:
      chart: raw
      version: "2.0.2"
      sourceRef:
        kind: HelmRepository
        name: bedag
        namespace: flux-system
  dependsOn:
    - name: opentelemetry-operator
      namespace: opentelemetry-operator-system
  interval: 5m
  values:
    resources:
      - apiVersion: opentelemetry.io/v1alpha1
        kind: OpenTelemetryCollector
        metadata:
          name: logs-collector
          namespace: opentelemetry-operator-system
        spec:
          mode: daemonset
          serviceAccount: logs-collector
          volumes:
            - name: varlogpods
              hostPath:
                path: /var/log/pods
            - name: varlibdockercontainers
              hostPath:
                path: /var/lib/docker/containers
            - name: varlogcontainers
              hostPath:
                path: /var/log/containers
            - name: otel-logs-storage
              emptyDir: {}
          volumeMounts:
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlogcontainers
              mountPath: /var/log/containers
              readOnly: true
            - name: otel-logs-storage
              mountPath: /otel-logs-storage
          config: |
            receivers:
              filelog:
                include:
                  - /var/log/pods/*/*/*.log
                exclude:
                  # Exclude logs from the logging system itself to prevent loops
                  - /var/log/pods/opentelemetry-operator-system_*/*/*.log
                  - /var/log/pods/flux-system_*/*/*.log
                start_at: end
                include_file_path: true
                include_file_name: false
                operators:
                  # Handle multiline logs - merge lines starting with whitespace
                  - type: recombine
                    id: multiline-merger
                    combine_field: body
                    is_first_entry: 'body matches "^\\S"'
                  # Parse container logs using the standard container operator
                  - type: container
                    id: container-parser
                storage: file_storage

            processors:
              batch:
                timeout: 1s
                send_batch_size: 1024
              
              resource:
                attributes:
                  - key: service.name
                    value: kubernetes-logs
                    action: upsert
                  - key: deployment.environment
                    value: dev
                    action: upsert
              
              k8sattributes:
                auth_type: "serviceAccount"
                passthrough: false
                extract:
                  metadata:
                    - k8s.pod.name
                    - k8s.pod.uid
                    - k8s.deployment.name
                    - k8s.namespace.name
                    - k8s.node.name
                    - k8s.pod.start_time
                  labels:
                    - tag_name: app
                      key: app
                      from: pod
                    - tag_name: version
                      key: version
                      from: pod
                pod_association:
                  - sources:
                      - from: resource_attribute
                        name: k8s.pod.name
                  - sources:
                      - from: resource_attribute
                        name: k8s.namespace.name

            extensions:
              file_storage:
                directory: /otel-logs-storage
                timeout: 10s
                create_directory: true

            exporters:
              otlp:
                endpoint: otel-collector.tinyolly.svc.cluster.local:4317
                tls:
                  insecure: true
                sending_queue:
                  enabled: true
                  num_consumers: 4
                  queue_size: 100
                retry_on_failure:
                  enabled: true
                  initial_interval: 10ms
                  max_interval: 1m
                  max_elapsed_time: 10m

            service:
              extensions: [file_storage]
              pipelines:
                logs:
                  receivers: [filelog]
                  processors: [k8sattributes, resource, batch]
                  exporters: [otlp]

      - apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: logs-collector
          namespace: opentelemetry-operator-system

      - apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        metadata:
          name: logs-collector
        rules:
        - apiGroups: [""]
          resources: ["pods", "namespaces"]
          verbs: ["get", "watch", "list"]
        - apiGroups: ["apps"]
          resources: ["replicasets"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["extensions"]
          resources: ["replicasets"]
          verbs: ["get", "list", "watch"]

      - apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: logs-collector
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: logs-collector
        subjects:
        - kind: ServiceAccount
          name: logs-collector
          namespace: opentelemetry-operator-system