apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: strimzi-operator
spec:
  releaseName: strimzi-operator
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.49.1
      sourceRef:
        kind: HelmRepository
        name: strimzi-charts
        namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 5m
  values:
    # Add any custom values here
    watchAnyNamespace: true
