apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kafka-dev
  namespace: kafka
spec:
  interval: 5m
  chart:
    spec:
      chart: strimzi-cluster-instance
      sourceRef:
        kind: HelmRepository
        name: localregistry
        namespace: flux-system
      version: "${strimzi_cluster_instance_version}"
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: trust-manager
      namespace: cert-manager
    - name: cluster-issuer
      namespace: cert-manager
    - name: strimzi-operator
      namespace: strimzi-operator
  values:
    kafka:
      additionalListeners:
      - name: ext4tls
        port: 9094
        type: ingress
        tls: true
        configuration:
          bootstrap:
            host: kafka-dev-bootstrap.domain.local  
          brokerCertChainAndKey:
            secretName: kafka-dev-sci-external
            certificate: tls.crt
            key: tls.key  
          hostTemplate: broker-{nodeId}.domain.local    
    certificates:
      listeners:
        internal:
          enabled: true
          issuerRef:
            name: selfsigned-cluster-issuer
            kind: ClusterIssuer
            group: cert-manager.io
        external:
          enabled: true
          issuerRef:
            name: selfsigned-cluster-issuer
            kind: ClusterIssuer
            group: cert-manager.io
