apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kafka-dev
  namespace: kafka
spec:
  interval: 5m
  chart:
    spec:
      chart: strimzi-cluster-instance
      sourceRef:
        kind: HelmRepository
        name: localregistry
        namespace: flux-system
      version: "${strimzi_cluster_instance_version}"
  values:
    # Add your custom values here
