apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: strimzi-access-operator
spec:
  releaseName: strimzi-access-operator
  chart:
    spec:
      chart: strimzi-access-operator
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: strimzi-charts
        namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
    - name: strimzi-operator
      namespace: strimzi-operator
  interval: 5m
  values:
    # Add any custom values here
    watchAnyNamespace: true
