apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: trust-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: "0.17.1"
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    crds:
      enabled: true  
