name: Release strimzi-cluster-instance

on:
  push:
    tags:
      - 'strimzi-cluster-instance/v*'

jobs:
  release:
    uses: ./.github/workflows/helm-chart-release.yml
    with:
      chart-name: strimzi-cluster-instance
      chart-path: ./strimzi-cluster-instance
    secrets: inherit
